before_script:
  - eval $(ssh-agent -s) 
  - echo "$SSH_PRIVATE_KEY" | base64 --decode | ssh-add - 
  - ssh-add -l
  - npm install

stages:
  - local-test
  
Lint Run:
  image: node:8.9
  stage: local-test
  script:
    - npm run ci:lint

Unit Test Run:
  image: node:8.9
  stage: local-test
  script:
    - npm run ci:test
